import_from_git(
  url: 'http://git.ppdaicorp.com/testFastlane/fastlane.git',
  branch: 'master'
)

fastlane_version "2.38.1"

default_platform :ios

platform :ios do
	desc 'build dynamic framework'
	lane :build do
		build_framework(project: '${POD_NAME}')
	end

	desc 'publish lib of source'
	lane :publish do |options|
		version = options[:version]
		ppd_release_lib(
			version:version,
			project:'${POD_NAME}'
		)
	end

	desc 'publish fmk'
	lane :publish_fmk do |options|
		version = options[:version]
		ppd_release_fmk(
			version:version,
			project:'${POD_NAME}'
		)
	end
end